ifeq ($(TARGET_BOOTLOADER_BOARD_NAME),atlas40)

LOCAL_PATH := $(call my-dir)

ifeq ($(BOARD_RECOVERY_RMT_STORAGE),true)
include $(CLEAR_VARS)
LOCAL_MODULE := rmt_storage_recovery
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES_LOCAL
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)
endif
endif
